name: Build LogGuard SOC EXE

# Запуск по пушу в main или вручную
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1️⃣ Проверка репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2️⃣ Установка Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8.10'

    # 3️⃣ Установка зависимостей
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # 4️⃣ Сборка EXE
    - name: Build EXE (OneFile)
      run: |
        pyinstaller --noconfirm --onefile --windowed ^
        --icon=assets/logguard_icon.ico ^
        source/main.py

    # 5️⃣ Альтернатива: сборка в папку (ускоренный запуск)
    #- name: Build EXE (Folder)
    #  run: pyinstaller --noconfirm --windowed --icon=assets/logguard_icon.ico main.py

    # 6️⃣ Загрузка артефакта
    - name: Upload EXE artifact
      uses: actions/upload-artifact@v4
      with:
        name: LogGuard_SOC_EXE
        path: dist/main.exe
